### ISSUE TITLE
hello from the owner of canhazip.com

### ISSUE THREAD

**Issue by xxdesmus** [PoppySeedPlehzr/lola#1]
Hi folks,

I'm the owner of canhazip.com -- took me a while, but I eventually tracked down where the mysterious traffic I was seeing was coming from. :) 

I was tracking down things such as https://www.reverse.it/search?query=lola.exe  and https://www.hybrid-analysis.com/sample/cc011252eb1f8e028a99947521e104fe696a190e30ba6c79b32a381c21799c3f?environmentId=2
and https://www.hybrid-analysis.com/search?query=domain%3Acanhazip.com   that were reporting my domain involved with malware. 

I'm glad to see/hear that it was actually a school project!

Anyway, just wanted to say Hi!

Cheers,
Justin

**Comment by muffins** [comment]
Hey There!

That's pretty awesome you found me!  The sample was used for a competition called High School forensics, sorry for using yer site, it's just so great :-D

Honestly it's kinda cool to see my malware hanging out in some of the analysis sites!

Thanks for reaching out!
